<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2017
 *
 * Generated from xml/schema/CRM/Memberperiod/MembershipPeriod.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:c12dc2b280af8c7aaf12ca4b91bb82fc)
 */

/**
 * Database access object for the MembershipPeriod entity.
 */
class CRM_Memberperiod_DAO_MembershipPeriod extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  static $_tableName = 'civicrm_membership_period';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  static $_log = TRUE;

  /**
   * Unique MembershipPeriod ID
   *
   * @var int unsigned
   */
  public $id;

  /**
   * Start date of membership period
   *
   * @var date
   */
  public $start_date;

  /**
   * End date of membership period
   *
   * @var date
   */
  public $end_date;

  /**
   * FK to Membership
   *
   * @var int unsigned
   */
  public $membership_id;

  /**
   * End date of membership period
   *
   * @var datetime
   */
  public $created_at;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_membership_period';
    parent::__construct();
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static ::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'membership_id', 'civicrm_membership', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'Unique MembershipPeriod ID',
          'required' => TRUE,
          'table_name' => 'civicrm_membership_period',
          'entity' => 'MembershipPeriod',
          'bao' => 'CRM_Memberperiod_DAO_MembershipPeriod',
          'localizable' => 0,
        ],
        'membership_period_start_date' => [
          'name' => 'start_date',
          'type' => CRM_Utils_Type::T_DATE,
          'title' => ts('Membership Period Start Date'),
          'description' => 'Start date of membership period',
          'import' => TRUE,
          'where' => 'civicrm_membership_period.start_date',
          'headerPattern' => '',
          'dataPattern' => '',
          'export' => TRUE,
          'table_name' => 'civicrm_membership_period',
          'entity' => 'MembershipPeriod',
          'bao' => 'CRM_Memberperiod_DAO_MembershipPeriod',
          'localizable' => 0,
        ],
        'membership_period_end_date' => [
          'name' => 'end_date',
          'type' => CRM_Utils_Type::T_DATE,
          'title' => ts('Membership Period End Date'),
          'description' => 'End date of membership period',
          'import' => TRUE,
          'where' => 'civicrm_membership_period.end_date',
          'headerPattern' => '',
          'dataPattern' => '',
          'export' => TRUE,
          'table_name' => 'civicrm_membership_period',
          'entity' => 'MembershipPeriod',
          'bao' => 'CRM_Memberperiod_DAO_MembershipPeriod',
          'localizable' => 0,
        ],
        'membership_id' => [
          'name' => 'membership_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'FK to Membership',
          'table_name' => 'civicrm_membership_period',
          'entity' => 'MembershipPeriod',
          'bao' => 'CRM_Memberperiod_DAO_MembershipPeriod',
          'localizable' => 0,
          'FKClassName' => 'CRM_Member_DAO_Membership',
        ],
        'membership_period_created_at' => [
          'name' => 'created_at',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => ts('Membership Period ctreated time'),
          'description' => 'End date of membership period',
          'import' => TRUE,
          'where' => 'civicrm_membership_period.created_at',
          'headerPattern' => '',
          'dataPattern' => '',
          'export' => TRUE,
          'table_name' => 'civicrm_membership_period',
          'entity' => 'MembershipPeriod',
          'bao' => 'CRM_Memberperiod_DAO_MembershipPeriod',
          'localizable' => 0,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'membership_period', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'membership_period', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
